/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106764-g40f2ea971f-20220502"
#endif /* AVUTIL_FFVERSION_H */
